[package]
name = "engine_p2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "p2p_server"
path = "bin/p2p_server.rs"
